version: '3'
services:
  web:
    build: .
    ports:
     - "5000:80"
    volumes:
     - .:/code

  redis:
    image: "redis:alpine"

  proxy:
    image: "nginx"
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always